apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ledger-core-deployment.yaml
  - sanctions-screening-deployment.yaml
  - networkpolicy.yaml
configMapGenerator:
  - name: ledger-core-config
    literals:
      - ENVIRONMENT=base
      - OUTBOX_TOPIC=payo.ledger.transactions.v1
